-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 96fb7fa10f2f4c11ed33482a9ad7474251e5e97f
    hooks:
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
